version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: dependabot-update
