name: test-lambda-a@CI/CD
on:
  push:
    branches:
      - test
jobs:
  test-lambda-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo 'running test lambda-a'