name: dev-lambda-b@CI/CD
on:
  push:
    branches:
      - development
jobs:
  dev-lambda-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo 'running dev lambda-b'