name: paths-filter-dev-feature-a-lambda-a@CI/CD
on:
  push:
    branches:
      - development
jobs:
  dev-feature-a-lambda-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: echo 'running development feature-a lambda-a'